# Generated by Django 2.0.6 on 2018-06-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20180602_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='request_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('request_sent', 'request_sent'), ('success', 'success'), ('failed', 'failed')], default='new', max_length=20),
        ),
    ]
