# Generated by Django 2.0.6 on 2018-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20180602_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
